import Head from "next/head";
import Home from "./home/Home";
import { ActiveItemsProvider } from "@/contexts/ActiveItemsStoreContext";
// import '../styles/globals.css'

export default function Landing() {
  return (
    <>
      <Head>
        <title>Product Pilot </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ActiveItemsProvider>
        <main>
          <Home />
        </main>
      </ActiveItemsProvider>
    </>
  );
}